name: Build LaTeX PDF

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_PAT: ${{ secrets.REPO_PAT || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Get Git commit hash
        run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update version in main.tex
        run: |
          sed -i "s/\\\\newcommand{\\\\gitversion}{Unknown}/\\\\newcommand{\\\\gitversion}{${GIT_HASH}}/" main.tex

      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode main.tex
          bibtex main || true
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-PDF
          path: main.pdf

      - name: Commit & push PDF (GITHUB_TOKEN or PAT fallback)
        if: success()
        env:
          GIT_HASH: ${{ env.GIT_HASH }}
          REPO_PAT: ${{ secrets.REPO_PAT || '' }}
        run: |
          git config user.name "swe-developer"
          git config user.email "anna.developer2354@gmail.com"
          mkdir -p builds
          mv -f main.pdf builds/document_${GIT_HASH}.pdf
          git add builds/document_${GIT_HASH}.pdf
          git commit -m "Auto-build PDF for commit ${GIT_HASH}" || echo "No changes to commit"

          if [ -n "${REPO_PAT}" ]; then
            echo "Using PAT to push"
            git remote set-url origin https://x-access-token:${REPO_PAT}@github.com/${{ github.repository }}.git
            git push origin HEAD:main
          else
            echo "Using GITHUB_TOKEN to push"
            git push origin HEAD:main || echo "Push failed with GITHUB_TOKEN"
          fi

